id: I4A66B6AF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T06:07:36+00:00'
last_modified: '2022-06-08T01:27:14.662055+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ74390
  title: བརྡའི་བྱེ་བྲག་རྣམ་པར་ཕྱེ་བའི་ཚིག་ལེའུར་བྱས་པ་སྨྲ་བའི་རྒྱན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    3BE5:
      image_group_id: I4CZ74392
      title: ''
      total_pages: 378
      order: 1
      base_file: 3BE5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
