id: I4A66B6AF
legacy_id: P004490
ocr_import_info:
  bdrc_scan_id: W4CZ74390
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T06:04:59'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T21:05:16.327779+00:00'
last_modified: 2022-09-04 05:05:28.918828
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W4CZ74390
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW4CZ74390
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བརྡའི་བྱེ་བྲག་རྣམ་པར་ཕྱེ་བའི་ཚིག་ལེའུར་བྱས་པ་སྨྲ་བའི་རྒྱན།
  author: པྲ་ཏི་དགེ་བཤེས་རིན་ཆེན་དོན་གྲུབ།
statistics:
  ocr_word_mean_confidence_index: 0.6321560483986473
  ocr_word_median_confidence_index: 0.6700000166893005
quality: null
bases:
  I4CZ74392:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CZ74392
      total_pages: 378
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4CZ74392.txt
    statistics:
      ocr_word_median_confidence_index: 0.6700000166893005
      ocr_word_mean_confidence_index: 0.6321560483986473
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
