id: P004490
initial_creation_type: ocr
source_metadata:
  id: bdr:W4CZ74390
  title: བརྡའི་བྱེ་བྲག་རྣམ་པར་ཕྱེ་བའི་ཚིག་ལེའུར་བྱས་པ་སྨྲ་བའི་རྒྱན།
  author: ''
  volumes:
    f7c9f58f418643e38d9e36308e5ba926:
      image_group_id: I4CZ74392
      title: ''
      volume_number: 1
      total_pages: 378
